server:
  port: 9090
spring:
  datasource:
    username: faturalarim
    password:
    url: jdbc:h2:mem:faturalarimdb

  messages:
    encoding: UTF-8

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

sample:
  rabbitmq:
    exchange: default
    queue: sample.queue
    routingKey: sample.routingKey
